name: Keepalive Workflow

on:
  schedule:
    - cron: '0 0 */40 * *'
  workflow_dispatch:

jobs:
  cronjob-based-workflow:
    runs-on: ubuntu-latest
    permissions:
      actions: write # Δικαίωμα διαχείρισης workflows στο GitHub
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          auto_write_check: false # Παράκαμψη του ελέγχου που προκαλεί το 403
